context:
  version: 0.4.0

package:
  name: tre-command
  version: ${{ version }}

source:
  url: https://github.com/dduan/tre/archive/v${{ version }}.tar.gz
  sha256: 280243cfa837661f0c3fff41e4a63c6768631073c9f6ce9982d9ed08e038788a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - tre --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Tree command, improved
  homepage: https://github.com/dduan/tre
  repository: https://github.com/dduan/tre

extra:
  recipe-maintainers:
    - danielnachun
